apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: github-org-import
  title: Import GitHub Organization Repos
  description: Creates a Location using github-discovery to ingest catalog-info.yaml from every repo in a GitHub org.
  tags:
    - catalog
    - github
    - discovery
spec:
  owner: group:default/core-team
  type: catalog

  parameters:
    - title: Import settings
      required:
        - githubOrg
        - publishMode
      properties:
        publishMode:
          title: Publish mode
          type: string
          description: Choose whether to create a new repo (and register it) or open a PR into an existing repo/folder.
          default: createRepo
          enum:
            - createRepo
            - pullRequest
          enumNames:
            - Create a new repository
            - Open a pull request into an existing repository

        githubOrg:
          title: Organization
          type: string
          description: GitHub organization to discover repositories from.
          pattern: '^[A-Za-z0-9](?:[A-Za-z0-9-]{0,38}[A-Za-z0-9])?$'
        githubHost:
          title: GitHub host
          type: string
          description: GitHub host for discovery (use github.com or your GHE host).
          default: github.com
        defaultBranch:
          title: Default branch
          type: string
          description: Branch to look for catalog-info.yaml in each repo.
          default: main
        catalogInfoPath:
          title: Catalog file path
          type: string
          description: Path to the catalog descriptor in each repo.
          default: catalog-info.yaml

        createRepoUrl:
          title: New repository location
          type: string
          description: GitHub repo to create that will contain the discovery Location (e.g. github.com?owner=7KGroup&repo=org-catalog-discovery)
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
            requestUserCredentials:
              secretsKey: USER_OAUTH_TOKEN

        existingRepoUrl:
          title: Existing repository location
          type: string
          description: Existing GitHub repo to open a PR against (e.g. github.com?owner=7KGroup&repo=backstage-catalog)
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
            requestUserCredentials:
              secretsKey: USER_OAUTH_TOKEN
        existingTargetPath:
          title: Target folder in existing repo
          type: string
          description: Folder path to add the generated files into (e.g. catalog/github-discovery/7KGroup). Leave empty to write to repo root.
          default: catalog/github-discovery
        pullRequestBranchName:
          title: PR branch name
          type: string
          default: backstage/import-github-org
        pullRequestTargetBranchName:
          title: PR target branch
          type: string
          default: main

        description:
          title: Description
          type: string
          default: Backstage catalog discovery location for importing all repos from a GitHub organization.

      dependencies:
        publishMode:
          oneOf:
            - properties:
                publishMode:
                  const: createRepo
              required:
                - createRepoUrl
            - properties:
                publishMode:
                  const: pullRequest
              required:
                - existingRepoUrl
                - existingTargetPath
                - pullRequestBranchName
                - pullRequestTargetBranchName

  steps:
    - id: fetch
      name: Fetch skeleton
      action: fetch:template
      input:
        url: ./skeleton
        templateFileExtension: .njk
        values:
          githubOrg: ${{ parameters.githubOrg }}
          githubHost: ${{ parameters.githubHost }}
          defaultBranch: ${{ parameters.defaultBranch }}
          catalogInfoPath: ${{ parameters.catalogInfoPath }}
          description: ${{ parameters.description }}

    - id: publish
      name: Publish to GitHub (new repo)
      if: ${{ parameters.publishMode == 'createRepo' }}
      action: publish:github
      input:
        repoUrl: ${{ parameters.createRepoUrl }}
        description: ${{ parameters.description }}
        defaultBranch: main
        token: ${{ secrets.USER_OAUTH_TOKEN }}

    - id: publishPr
      name: Publish to GitHub (pull request)
      if: ${{ parameters.publishMode == 'pullRequest' }}
      action: publish:github:pull-request
      input:
        repoUrl: ${{ parameters.existingRepoUrl }}
        branchName: ${{ parameters.pullRequestBranchName }}
        targetBranchName: ${{ parameters.pullRequestTargetBranchName }}
        title: Import GitHub org discovery Location
        description: ${{ parameters.description }}
        sourcePath: .
        targetPath: ${{ parameters.existingTargetPath }}
        token: ${{ secrets.USER_OAUTH_TOKEN }}

    - id: register
      name: Register in catalog
      if: ${{ parameters.publishMode == 'createRepo' }}
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish'].output.repoContentsUrl }}
        catalogInfoPath: /catalog-info.yaml

  output:
    links:
      - title: Repository (new repo)
        url: ${{ steps['publish'].output.remoteUrl }}
      - title: Pull request (existing repo)
        url: ${{ steps['publishPr'].output.remoteUrl }}/pull/${{ steps['publishPr'].output.pullRequestNumber }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps['register'].output.entityRef }}

