apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: backstage-catalog-root
  description: Root location for all catalog entities and templates in this repo
spec:
  type: url
  targets:
    - ./catalog/acme-corp.yaml
    - ./catalog/all.yaml