apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: platform-api-ci
  title: Platform API CI
  description: CI pipeline for platform-api
spec:
  type: github-actions
  owner: group:platform
  system: developer-platform
  dependsOn:
    - component:platform-api
