apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: org-identities
  description: Collection of all identity entities (groups/users)
spec:
  type: url
  targets:
    - ./acme/org.yaml
    - ./acme/platform.yaml
    - ./acme/platform-admin-team.yaml
    - ./acme/joaodss-user.yaml
