apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: platform
  title: Platform Engineering
  description: Owns the SaaS developer platform
spec:
  type: team
  profile:
    displayName: Platform Engineering
  children: []
