apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: org-templates
  description: Collection of all scaffolder templates
spec:
  type: url
  targets:
    - ./new-domain/template.yaml
    - ./new-system/template.yaml
