apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: example-db
  description: Example database resource
spec:
  type: database
  owner: group:default/cloud-infrastructure-team
  system: developer-platform
