apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: heimdall-application-plane
  description: Application plane for 7kgroup
spec:
  type: plane
  profile:
    displayName: Application Plane
  parent: sevenk-group
  children:
    - application-team

---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: application-team
  description: Team responsible for application lifecycle and feature delivery
spec:
  type: team
  profile:
    displayName: Application Team
  parent: heimdall-application-plane
  children: []
