apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: inari
  description: Inari company organization
  annotations:
    github.com/org: Inari
spec:
  type: organization
  profile:
    displayName: Inari