apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: core-team
  description: >-
    Cross-functional core team responsible for client engagement, release
    management, quality assurance, security oversight, and continuous improvement.
spec:
  type: team
  profile:
    displayName: Core Team
  parent: inari
  children: []
