apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: core-team
  description: Core team at Inari
spec:
  type: team
  profile:
    displayName: Core Team
  parent: inari
  children: []
  members:
    - joaodss
