apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: joaodss
  description: Platform Admin at Inari
spec:
  profile:
    displayName: Joao Santos
    email: joaodss@live.com.pt
  memberOf:
    - core-team
