apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: joaodss
  description: Platform Admin at Inari
spec:
  profile:
    displayName: Noone
    email: joao.santos@7kgroup.org
  memberOf:
    - core-team
